spring:
 application:
    name: category-service
 profiles:
    active:
    - :dev 
 cloud:
  config:
   uri: http://localhost:8888
  
server:
  port: 9090
 
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
        
        
logging:
  file:
    path: C:/App/CLI-Cart/log Files
    name: category.log
     


   
   